#!/usr/bin/env bash

PUBLIC_DIR=$(pwd)/public
SRC_DIR=$(pwd)/src

cd "$SRC_DIR"

if [ ! -f "$SRC_DIR/data/general/git-projects.json" ]; then
  curl -s https://api.github.com/users/dipakw/repos \
    -o "$SRC_DIR/data/general/git-projects.json"
fi

php index.php > "$PUBLIC_DIR/index.html"
